#!/usr/bin/env python

import os
import subprocess
import sys

def main():
  if len(sys.argv) <= 1:
    default_remote = "origin"
  else:
    default_remote = sys.argv[1]
  if len(sys.argv) <= 2:
    default_remote = "master"
  else:
    default_remote = sys.argv[2]
  if not os.path.exists(".gitmanifest"):
    print("mergeall: missing .gitmanifest")
    return
  with open(".gitmanifest") as manifest:
    for entry in manifest:
      entry = entry.strip()
      if not os.path.exists(entry):
        print("mergeall: warning: missing repository '{}'".format(entry))
        continue
      print("mergeall: descending into '{}'...".format(entry))
      args = ["git", "merge", default_remote, default_branch]
      p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=entry)
      p.wait()
      ret = p.returncode
      print("mergeall:   return code: {}".format(ret))

if __name__ == "__main__":
  main()
